name: Selenium Java CI

on:
  workflow_dispatch:
  push:
    branches: [ "Practice" ]
  pull_request:
    branches: [ "Practice" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Headless Selenium Tests
        run: mvn clean test
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: surefire-reports
          path: target/surefire-reports/
